# Generated by Django 2.0.9 on 2019-01-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='td_no',
            field=models.CharField(default='td_no', max_length=5),
        ),
    ]
