# Generated by Django 2.0.9 on 2019-01-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todo_td_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='to_do',
            field=models.TextField(),
        ),
    ]
