# Generated by Django 2.0.9 on 2019-08-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_auto_20190106_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='link_code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
