# Generated by Django 2.0.9 on 2019-08-28 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_auto_20190828_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='link_code',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
