# Generated by Django 2.0.9 on 2019-08-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0008_auto_20190828_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='lang',
            field=models.CharField(choices=[('c', 'C'), ('cpp', 'CPP'), ('py', 'Python')], default=' ', max_length=10),
            preserve_default=False,
        ),
    ]
