# Generated by Django 2.0.9 on 2019-08-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0009_todo_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='lang',
            field=models.CharField(choices=[('c', 'C'), ('cpp', 'CPP'), ('py', 'Python')], default='c', max_length=10),
        ),
    ]
