# Generated by Django 2.0.9 on 2019-09-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0010_auto_20190830_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='lang',
            field=models.CharField(choices=[('c', 'c'), ('cpp', 'c++'), ('csharp', 'c#'), ('java', 'java'), ('js', 'javaScript'), ('php', 'php'), ('py', 'python'), ('sql', 'sql')], default='c', max_length=10),
        ),
    ]
