# Generated by Django 2.0.9 on 2019-09-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0011_auto_20190911_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='lang',
            field=models.CharField(choices=[('c', 'C'), ('cpp', 'C++'), ('csharp', 'C#'), ('java', 'Java'), ('js', 'JavaScript'), ('php', 'PHP'), ('py', 'Python'), ('sql', 'SQL')], default='c', max_length=10),
        ),
    ]
