# Generated by Django 2.0.9 on 2019-09-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0015_auto_20190911_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(default='untitled', max_length=40),
        ),
    ]
